export const positiveTagWeights: Record<string, number> = {
    "en:green-dot": 0.4,
    "green":0.4,
    "dot":0.4,
    "plant-based": 0.4,
    "fresh":0.3,
    "en:organic": 0.4,
    "en:eu-organic": 0.5,
    "bio": 0.5,
    "natural": 0.3,
    "naturel":0.3,
    "organic": 0.4,
    "recyclable": 0.4,
    "sans": 0.2,
    "vert": 0.2,
    "water":0.1,
    "usda":0.5,
    "fruits":0.35,
    "vegetables":0.35,
    "agriculture":0.4,
    "biologique":0.4,
    "tournesol":0.2,
    "colza": 0.15,

  }

export const negativeTagWeights: Record<string, number> = {
    "plastique": 0.5,
    "plastic": 0.5,
    "acid": 0.3,
    "acide": 0.3,
    "citrique": 0.2,
    "e330": 0.2,
    "sodium": 0.2,
    "carton": 0.2,
    "arôme": 0.4,
    "arômes": 0.4,
    "additive": 0.5,
    "sachet": 0.3,
    "canned":0.2,
    "cereals":0.1,
    "beverages":0.2,
    "gluten":0.05,
    "sucre":0.35,
    "sugary":0.35,
    "snacks":0.1,
    "huile":0.3,
    "farine":0.2,
    "diaries":0.3,
    "meats":0.35,
    "viande":0.35,
    "poudre":0.1,
    "cheeses":0.3,
    "glucose":0.1,
    "groceries":0.2,
    "sirop":0.2,
    "amidon":0.1,
    "frozen":0.3,
    "verre":0.15,
    "lait":0.3,
    "desserts": 0.4,
    "cacao": 0.4,
    "potassium": 0.1,
    "sauces": 0.3,
    "alcoholic": 0.45,
    "barquette": 0.3,
    "jus": 0.3,
    "chocolates": 0.45,




  }


export const tagDisplayMap: Record<string, string> = {
  "en:green-dot": "Green Dot (Eco Symbol)",
  "green": "Green Dot (Eco Symbol)",
  "dot": "Green Dot (Eco Symbol)",
  "plant-based": "Plant Based",
  "fresh": "Fresh",
  "en:organic": "Organic",
  "en:eu-organic": "EU Organic Certified",
  "bio": "Biodegradable",
  "natural": "Natural",
  "naturel": "Natural",
  "organic": "Organic",
  "recyclable": "Recyclable",
  "sans": "Without Additives",
  "vert": "Green",
  "water": "Water",
  "usda": "USDA Certified",
  "fruits": "Fruits",
  "vegetables": "Vegetables",
  "agriculture": "Agricultural Product",
  "biologique": "Organic",
  "tournesol": "Sunflower",
  "colza": "Rapeseed",
  "plastique": "Plastic",
  "plastic": "Plastic",
  "acid": "Acid",
  "acide": "Acid",
  "citrique": "Citric Acid",
  "e330": "Citric Acid",
  "sodium": "Sodium",
  "carton": "Cardboard",
  "arôme": "Aroma (Flavoring)",
  "arômes": "Aroma (Flavoring)",
  "additive": "Additive / Preservative",
  "sachet": "Sachet (Small Packet)",
  "canned": "Canned Food",
  "cereals": "Cereals",
  "beverages": "Beverages",
  "gluten": "Gluten",
  "sucre": "Sugar",
  "sugary": "Sugar",
  "snacks": "Snacks",
  "huile": "Oil",
  "farine": "Flour",
  "diaries": "Dairy",
  "meats": "Meat",
  "viande": "Meat",
  "poudre": "Powder",
  "cheeses": "Cheese",
  "glucose": "Glucose",
  "groceries": "Groceries",
  "sirop": "Syrup",
  "amidon": "Starch",
  "frozen": "Frozen",
  "verre": "Glass",
  "lait": "Milk",
  "desserts": "Desserts",
  "cacao": "Cocoa",
  "potassium": "Potassium",
  "sauces": "Sauces",
  "alcoholic": "Beverages",
  "barquette": "Barquette (Tray)",
  "jus": "Juice",
  "chocolates": "Chocolates"
}
