export const positiveTags = [
  "en:green-dot",
  "green",
  "dot",
  "plant-based",
  "fresh",
  "en:organic",
  "en:eu-organic",
  "bio",
  "natural",
  "naturel",
  "organic",
  "recyclable",
  "sans",
  "vert",
  "water",
  "usda",
  "fruits",
  "vegetables",
  "agriculture",
  "biologique",
  "tournesol",
  "colza",
];

export const negativeTags = [
  "plastique",
  "plastic",
  "acid",
  "acide",
  "citrique",
  "e330",
  "sodium",
  "carton",
  "arôme",
  "arômes",
  "additive",
  "sachet",
  "canned",
  "cereals",
  "beverages",
  "gluten",
  "sucre",
  "sugary",
  "snacks",
  "huile",
  "farine",
  "diaries",
  "meats",
  "viande",
  "poudre",
  "cheeses",
  "glucose",
  "groceries",
  "sirop",
  "amidon",
  "frozen",
  "verre",
  "lait",
  "desserts",
  "cacao",
  "potassium",
  "sauces",
  "alcoholic",
  "barquette",
  "jus",
  "chocolates",
];

export const tagDisplayMap: Record<string, string> = {
  "en:green-dot": "Green Dot (Eco Symbol)",
  "green": "Green Dot (Eco Symbol)",
  "dot": "Green Dot (Eco Symbol)",
  "plant-based": "Plant Based",
  "fresh": "Fresh",
  "en:organic": "Organic",
  "en:eu-organic": "EU Organic Certified",
  "bio": "Biodegradable",
  "natural": "Natural",
  "naturel": "Natural",
  "organic": "Organic",
  "recyclable": "Recyclable",
  "sans": "Without Additives",
  "vert": "Green",
  "water": "Water",
  "usda": "USDA Certified",
  "fruits": "Fruits",
  "vegetables": "Vegetables",
  "agriculture": "Agricultural Product",
  "biologique": "Organic",
  "tournesol": "Sunflower",
  "colza": "Rapeseed",
  "plastique": "Plastic",
  "plastic": "Plastic",
  "acid": "Acid",
  "acide": "Acid",
  "citrique": "Citric Acid",
  "e330": "Citric Acid",
  "sodium": "Sodium",
  "carton": "Cardboard",
  "arôme": "Aroma (Flavoring)",
  "arômes": "Aroma (Flavoring)",
  "additive": "Additive / Preservative",
  "sachet": "Sachet (Small Packet)",
  "canned": "Canned Food",
  "cereals": "Cereals",
  "beverages": "Beverages",
  "gluten": "Gluten",
  "sucre": "Sugar",
  "sugary": "Sugar",
  "snacks": "Snacks",
  "huile": "Oil",
  "farine": "Flour",
  "diaries": "Dairy",
  "meats": "Meat",
  "viande": "Meat",
  "poudre": "Powder",
  "cheeses": "Cheese",
  "glucose": "Glucose",
  "groceries": "Groceries",
  "sirop": "Syrup",
  "amidon": "Starch",
  "frozen": "Frozen",
  "verre": "Glass",
  "lait": "Milk",
  "desserts": "Desserts",
  "cacao": "Cocoa",
  "potassium": "Potassium",
  "sauces": "Sauces",
  "alcoholic": "Beverages",
  "barquette": "Barquette (Tray)",
  "jus": "Juice",
  "chocolates": "Chocolates"
}


const readTags:string[] = []

export const displayTags = [...positiveTags, ...negativeTags]
  .filter(tag => {
    if (readTags.includes(tagDisplayMap[tag]))
    {
      return false
    }
    else
    {
      readTags.push(tagDisplayMap[tag])
      return true
    }
})

export const tagsWithoutQuantity = [
  "Green Dot (Eco Symbol)",
  "EU Organic Certified",
  "USDA Certified",
]
